# config/services.yaml

# Parametros generales
parameters:
# Si querés, podés definir un parámetro intermedio
# weather.api_key: '%env(WEATHER_API_KEY)%'

services:
  # Configuración por defecto para todos los servicios
  _defaults:
    autowire: true      # inyección automática de dependencias
    autoconfigure: true # registra comandos, event subscribers, etc.

  # Hace que todas las clases en src/ estén disponibles como servicios
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Service\WeatherService:
    arguments:
      $apiKey: '%env(WEATHER_API_KEY)%'
